# Generated by Django 3.1.4 on 2020-12-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0004_auto_20201219_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dotbiz.parent_check'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dotbiz.category'),
        ),
    ]
