# Generated by Django 3.1.4 on 2020-12-19 13:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dotbiz', '0005_auto_20201219_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPage',
            new_name='MainPage',
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page_link', models.SlugField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keyword', models.TextField(blank=True, null=True)),
                ('as_child', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dotbiz.mainpage')),
                ('author', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
