# Generated by Django 3.1.4 on 2020-12-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0006_auto_20201219_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='parent_check',
            new_name='ParentCheck',
        ),
    ]
