# Generated by Django 3.1.4 on 2020-12-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0007_auto_20201220_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subpage',
            old_name='author',
            new_name='user',
        ),
    ]
