# Generated by Django 3.1.4 on 2020-12-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0009_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='page_link',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
