# Generated by Django 3.1.4 on 2020-12-21 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0011_auto_20201221_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='title_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
