# Generated by Django 3.1.4 on 2020-12-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0012_mainpage_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='page_link',
            new_name='slug',
        ),
    ]
