# Generated by Django 3.1.4 on 2020-12-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0013_auto_20201221_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='slug',
            new_name='page_link',
        ),
    ]
