# Generated by Django 3.1.4 on 2020-12-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0014_auto_20201222_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subpage',
            name='user',
        ),
    ]
