# Generated by Django 3.1.4 on 2020-12-25 17:02

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0015_auto_20201223_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_link',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='meta_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='meta_keyword',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
