# Generated by Django 3.1.4 on 2020-12-26 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0016_auto_20201226_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='as_child',
            new_name='parent_page',
        ),
        migrations.AlterField(
            model_name='subpage',
            name='meta_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subpage',
            name='meta_keyword',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subpage',
            name='page_link',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
