# Generated by Django 3.1.4 on 2020-12-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0017_auto_20201226_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='page_link',
            new_name='sub_page_link',
        ),
        migrations.RenameField(
            model_name='subpage',
            old_name='title',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='subpage',
            old_name='title_tag',
            new_name='sub_title_tag',
        ),
    ]
