# Generated by Django 3.1.4 on 2020-12-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0018_auto_20201226_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='parent',
            new_name='parent_check',
        ),
    ]
