# Generated by Django 3.1.4 on 2020-12-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0019_auto_20201226_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='subpage',
            name='parent_page',
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
        migrations.DeleteModel(
            name='ParentCheck',
        ),
        migrations.DeleteModel(
            name='SubPage',
        ),
    ]
