# Generated by Django 3.1.4 on 2020-12-27 14:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0020_auto_20201227_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tag', models.CharField(max_length=255)),
                ('page_link', models.SlugField(max_length=255, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('parent_check', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('meta_keyword', models.TextField()),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dotbiz.category')),
            ],
        ),
    ]
