# Generated by Django 3.1.4 on 2020-12-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0022_subpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='Post',
        ),
    ]
