# Generated by Django 3.1.4 on 2020-12-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0023_auto_20201227_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_check',
        ),
        migrations.DeleteModel(
            name='SubPage',
        ),
    ]
