# Generated by Django 3.1.4 on 2020-12-28 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0025_subpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_check',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
