# Generated by Django 3.1.4 on 2020-12-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0027_auto_20201229_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='sub_title',
            new_name='title',
        ),
    ]
