# Generated by Django 3.1.4 on 2020-12-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0028_auto_20201229_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='sub_page_link',
            new_name='page_link',
        ),
    ]
