# Generated by Django 3.1.4 on 2021-01-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0031_uploadedfile_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
    ]
