# Generated by Django 3.1.4 on 2021-01-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0032_remove_uploadedfile_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpage',
            old_name='sub_title_tag',
            new_name='title_tag',
        ),
    ]
