# Generated by Django 3.1.4 on 2021-01-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0033_auto_20210103_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
