# Generated by Django 3.1.4 on 2021-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0035_remove_category_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
