# Generated by Django 3.1.4 on 2021-01-06 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0037_auto_20210106_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
