# Generated by Django 3.1.4 on 2021-01-09 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0039_indexeditor_sidelinkforindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexeditor',
            name='meta_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexeditor',
            name='meta_keyword',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
