# Generated by Django 3.1.4 on 2021-01-09 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0040_auto_20210109_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexeditor',
            name='copyright_content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
