# Generated by Django 3.1.4 on 2021-01-09 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0041_indexeditor_copyright_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexeditor',
            name='title_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
