# Generated by Django 3.1.4 on 2021-01-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0045_dropdowncontent_dropdownname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stats',
            field=models.CharField(default='ACTIVE', max_length=255),
        ),
    ]
