# Generated by Django 3.1.5 on 2021-01-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotbiz', '0048_dropdowntag_dropdownurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdowntag',
            old_name='url',
            new_name='links',
        ),
    ]
